name: 'Problem Assigned'
description: 'Problem Assignee Recommendation'
inputs:
  token:
    description: 'Github Token'
    required: true
outputs:
  time:
    description: 'count'
    default: 0
runs:
  using: 'node12'
  main: 'index.js'